{% set name = "emicroml" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emicroml-{{ version }}.tar.gz
  sha256: 44056459b3893a8815b9bcb6fffc81b29843dc44485a45acb569ff1d6ef760f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - fakecbed >=0.3.6
    - kornia
    - h5pywrappers

test:
  imports:
    - emicroml
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/emicroml/
  summary: A Python library for training machine learning models for applications in electron microscopy.
  dev_url: https://github.com/mrfitzpa/emicroml
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
