{% set name = "emicroml" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emicroml-{{ version }}.tar.gz
  sha256: 792df7516051a221b546863c9666091f5d92f8193f125a7f5a00d37d74ba7c2f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - dask >=2024.4.1
    - pip
  run:
    - python >={{ python_min }}
    - fakecbed >=0.5.4
    - empix >=0.0.10
    - kornia
    - h5pywrappers
    - dask >=2024.4.1

test:
  imports:
    - emicroml
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/emicroml/
  summary: A Python library for training machine learning models for applications in electron microscopy.
  dev_url: https://github.com/mrfitzpa/emicroml
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
